version: '3.8'

services:
  ssh_server:
    build:
      context: ./ssh_server
    container_name: ssh_server
    hostname: ssh_server
    ports:
      - "2222:6205"
      - "8080:80"   

  ansible_controller:
    build:
      context: ./ansible_controller
    container_name: ansible_controller
    depends_on:
      - ssh_server
